### ISSUE TITLE
Standalone mode and performance issue

### ISSUE THREAD

**Issue by tanfengji-monarchtractor** [NVIDIA-AI-IOT/cuDLA-samples#7] opened 2023-10-06 09:38 UTC
Hi, I'm using jetpack 5.1.2. The hybrid mode works fine, but the standalone mode returns the error below:
<img width="603" alt="standalone_error" src="https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/143997403/de3d3e24-10fe-4353-a025-7e199dca2e31">
How may I fix this?

Besides, the performance is for hybrid mode is below:
<img width="568" alt="yolov5s_hybrid_23ms" src="https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/143997403/3b9b0adb-840e-4bf8-94c2-c20d34c0e4b9">
The MAP is 0.354 instead of 0.37+ mentioned in the README. Any possible reasons? Many thanks

**Comment by zerollzeng** [comment] 2023-11-16 07:03
Sorry for the late response, please pull the latest code and rebuild with `make validate_cudla_int8 USE_DLA_STANDALONE_MODE=1 USE_DETERMINISTIC_SEMAPHORE=1`

Root cause in https://github.com/NVIDIA-AI-IOT/cuDLA-samples/issues/5

**Comment by ou525** [comment] 2024-01-26 06:35
![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/f15ec830-2ed9-4f9f-8955-766187503146)
The latest code pulled, according to the above command, new problems appeared

**Comment by zerollzeng** [comment] 2024-01-27 11:45
Which JP/DOS version you are using?

**Comment by ou525** [comment] 2024-01-29 02:13
![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/fc62a960-d48c-4347-a8f9-d51c28dc399e)
@zerollzeng

**Comment by ou525** [comment] 2024-01-29 02:14
![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/2432e38d-4f71-46eb-a633-0dfeb823a9c1)
@zerollzeng

**Comment by ou525** [comment] 2024-01-29 02:14
![Uploading image.png…]()
@zerollzeng

**Comment by ou525** [comment] 2024-01-29 02:15
![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/f5bb436d-4154-4729-b62d-0622e09620bf)
@zerollzeng

**Comment by zerollzeng** [comment] 2024-02-01 13:04
I didn't test on JP 5.1. but JP 6.0 should work, could you please upgrade to it?

+ @lynettez

**Comment by ou525** [comment] 2024-02-02 01:37
By replacing the nvsci header file with version 6.0, I have successfully compiled and run

**Comment by zerollzeng** [comment] 2024-02-07 09:36
Glad you solve it, I'm closing this.

**Closed as completed by zerollzeng** 2024-02-07 09:36 UTC
Labels: triaged, fixed

**Comment by HelloChang1** [comment] 2024-04-07 08:32
> By replacing the nvsci header file with version 6.0, I have successfully compiled and run

hai，where can I find the the nvsci header file with version 6.0?
I only find in https://developer.nvidia.com/embedded/jetson-linux-r351 ,but it doesn't work.
